### ISSUE TITLE
Implement Sealed boxes

### ISSUE THREAD

**Issue by ChrisMacNaughton** [dnaq/sodiumoxide#100]
http://doc.libsodium.org/public-key_cryptography/sealed_boxes.html

It would be nice to be able to encrypt messages that the receiver could decrypt without being able to verify the encryptor

**Comment by dnaq** [comment]
If you don't need compatibility with libsodium then:

```
use sodiumoxide::crypto::box_;
pub fn sealed_box(plaintext: &[u8], serverpk: &box_::PublicKey) -> Vec<u8> {
    let (box_::PublicKey(ephemeral_pk), ephemeral_sk) = box_::gen_keypair();
    let nonce = box_::Nonce([0; box_::NONCEBYTES]);
    let ciphertext = box_::seal(plaintext, &nonce, serverpk, &ephemeral_sk);
    let mut ret = Vec::with_capacity(ephemeral_pk.len() + ciphertext.len());
    ret.extend(ephemeral_pk.iter());
    ret.extend(ciphertext.iter());
    ret
}

pub fn sealed_box_open(ciphertext: &[u8], serversk: &box_::SecretKey) -> Result<Vec<u8>, ()> {
    let ephemeral_pk = match box_::PublicKey::from_slice(&ciphertext[..box_::PUBLICKEYBYTES]) {
        None => return Err(()),
        Some(pk) => pk
    };
    let nonce = box_::Nonce([0; box_::NONCEBYTES]);
    box_::open(&ciphertext[box_::PUBLICKEYBYTES..], &nonce, &ephemeral_pk, serversk)
}
```
(code can be written cleaner, this is just a poc)

The nonce can be set to zero since we always generate a new ephemeral keypair each time we call this function. Libsodium doesn't work this way, it uses blake2b to hash the ephemeral and server public key and generates the nonce this way. However this is unnecessary. A quote from the NaCl documentation says that:

> There is no harm in having the same nonce for different messages if the {sender, receiver} sets are different. This is true even if the sets overlap. For example, a sender can use the same nonce for two different messages if the messages are sent to two different public keys.

If you really need compatibility with libsodium let me know.

**Comment by ChrisMacNaughton** [comment]
While compatibility would be cool I don't need it ;-) I was thinking about this prible overnight and came to basically the same solution you did, thanks!
