### ISSUE TITLE
Add sodium_malloc and friends

### ISSUE THREAD

**Issue by stouset** [dnaq/sodiumoxide#104]
https://github.com/jedisct1/libsodium/blob/master/src/libsodium/include/sodium/utils.h#L105

Not to mention the rest of `sodium/utils.h`. Feel free to steal my FFI code from [secrets](https://github.com/stouset/secrets/blob/master/src/sodium.rs), at which point I'll be able to simply depend on sodiumoxide instead of implementing it all myself.

**Comment by dnaq** [comment]
I've been holding off adding support for `sodium_malloc`, `sodium_mprotect`, et.al, since the most natural rust api to those functions would be a `SecureBox` type and to implement that in a good way we would need placement new, which AFAIK hasn't landed yet.

However, I'm not opposed to adding the bindings to `libsodium-sys`. If you would like to send a pull request I would merge it.

**Comment by stouset** [comment]
That's literally what I'm writing. If I can delegate the FFI portion of that to `sodiumoxide`, it would be fantastic.

**Comment by dnaq** [comment]
See #108
