### ISSUE TITLE
`secret` types unintentionally misleading

### ISSUE THREAD

**Issue by stouset** [dnaq/sodiumoxide#109]
It's worth discussing that simply wiping memory on `Drop` isn't really good enough for stack types. Any move virtually guarantees that their contents will be copied around, and it's impossible to track those situations in order to wipe memory contents.

I'm not sure what a good resolution of this would be. On the one hand, the existing implementation is misleading at best. On the other hand, not even attempting to sanitize memory after the fact is clearly worse. Ideally, sodiumoxide might just be a set of FFI wrappers, and then another library would implement safe Rust crypto operations on top of a set of much safer buffer types.

This isn't to say you should remove these protections, or rip this stuff out right now. I'm more just interested in your thoughts on the topic.

**Comment by dnaq** [comment]
In my opinion the threat model is:

1. We want a cryptographic system with forward secrecy.
2. If an attacker can somehow gain access to our system, all long-term keys will be compromised (all future connections if we're talking about a network protocol)
3. Also all active short-term keys will be compromised (all current connections).
4. We don't want any old short-term keys to be compromised (old connections) so that an attacker that has recorded the encrypted data can steal the keys afterwards and read it.

I believe there is only one correct solution to this problem and that is:

1. Fork off subprocesses to handle short term secrets.
2. Scrub all of their memory when the subprocess exits (would probably need a kernel patch).

All other ways to handle the problem will be patchy at best, even if we only use heap memory, make sure to clear it whenever needed and so on the compiler is still free (and needs to) put the data in actual registers when it's used. And whenever that happens a context-switch may happen which will cause these registers to be spilled to the stack. This we can't protect against with scrubbing.

What I've chosen to do in sodiumoxide is to implement the `Drop` trait for secret data to at least reduce the risk of old secrets being compromised. This is only to mitigate risk. The same thing will of course apply to your secrets library, it will mitigate risk somewhat more by not even allowing data to be paged out, but it can still be spilled to stack when used (and the stack pages can be paged out).

**Comment by burdges** [comment]
Interesting, thanks.  I'll bring the context switching up with tor folk as another reason to prioritize doing the crypto in a dedicated thread.  Although I'm sure Nick, etc. already know about this.  I'm curious if anyone has tried to minimize the switching issue by using floating point registers for secret material or something.

**Comment by mso42** [comment]
Sorry to necro this, but I was just about to file another issue about the same thing. I think it would be good to at least call out this gotcha in the docs somewhere, maybe around here?

https://github.com/sodiumoxide/sodiumoxide/blob/master/src/crypt/secretbox/xsalsa20poly1305.rs#L23
