### ISSUE TITLE
Return value of `sodiumoxide::init` is not documented

### ISSUE THREAD

**Issue by untitaker** [dnaq/sodiumoxide#118]
A look at its source code and then https://download.libsodium.org/doc/usage/index.html suggests that the program is supposed to abort if the return value is `-1`/`false`. IMO it's better if this is either documented in sodiumoxide, or if the bindings just panic.

Also it appears that there can be three return values:

>sodium_init() returns 0 on success, -1 on failure, and 1 is the library had already been initialized.

**Comment by dnaq** [comment]
`sodium_init()` can return three different values, but sodiumoxide only returns `true` or `false` since there's no need to differentiate between the two different success cases. We've been discussing a better solution for `init()` but have been holding off on it until static mutexes land in rust stable.
