### ISSUE TITLE
API for ephemeral encryption?

### ISSUE THREAD

**Issue by dpc** [dnaq/sodiumoxide#121]
Hi,

I can't find corresponding function to:

https://download.libsodium.org/doc/public-key_cryptography/sealed_boxes.html

**Comment by dnaq** [comment]
See #100 for a solution. If compatibility with libsodium is necessary for you then let me know and I'll add it to my todo list, otherwise let me know so I can close this issue.

**Comment by dpc** [comment]
I did something very much like it for a workaround. Still, why not just include it?

**Comment by dnaq** [comment]
I've been holding off on adding sealed box since I disagree with the choice of using blake2b for deriving an unnecessary nonce. I also don't want to implement a sealed box that isn't compatible with the one in sodium (since that would lead to a lot of confusion for users). That's why I ask if you have a use-case where compatibility with sealed boxes in sodium are required or not.

If someone needs it it's quite simple to add it in sodiumoxide, but I'd prefer not to add it unless necessary.

**Comment by dirvine** [comment]
I do have such a use case. It's when we have rust use of sodium that exposes an API to users at higher levels who may implement apps etc. via Rest API and use their own language implementations of sodium.  The current workaround will require they all implement the same workaround in their libs/languages. So it can prove cumbersome in this case.

**Comment by dpc** [comment]
What's the problem with blake2b? That calculating nonce is costly while it could be just zeros? I'd just do blake2b, stay compatible. This is crypto - being paranoid is a good thing, and anyone that cares about this one unneeded operation can just do it manually without it.

**Comment by dnaq** [comment]
I would say that there are two problems. The first one is that it's costly, and the second one is that it complicates the API. All of a sudden the `crypto_box_seal_open()` function needs to take in the receivers public and secret key instead of just the secret key (which breaks symmetry). I agree that these are minor issues, but I'm of the opinion that crypto primitives and API's should be as simple as possible to minimise the risk of mistakes made when using them.

I'm also not a big fan of `crypto_box_seal()` and `crypto_box_seal_open()` having different calling conventions than `crypto_box()` and `crypto_box_open()`, e.g. `crypto_box()` takes a zero-padded plaintext and the length of the padded plaintext whereas `crypto_box_seal()` takes an unpadded plaintext, puts it into a zero-padded ciphertext string and takes the length of the plaintext. This might sound like nitpicking, but one of the major issues with openssl is that functions have different calling conventions and different ways to signal errors, that's been the cause of some of the security issues with it. However I can hide the API differences in the bindings, so that's more of an issue with libsodium.

That being said, I'm currently adding bindings to these functions since a lot of people have requested them, but I'm still not a fan of the `crypto_box_seal()` implementation and API.
