### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by Sogomn** [dnaq/sodiumoxide#124]
```
Build failed, waiting for other jobs to finish...
failed to run custom build command for `libsodium-sys v0.0.10`
Process didn't exit successfully: `D:\Entwicklung\Rust\playground\target\debug\build\libsodium-sys-893da188a4086141\build-script-build` (exit code: 101)
--- stderr
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: "`\"pkg-config\" \"--libs\" \"--cflags\" \"libsodium\"` did not exit successfully: exit code: 1\n--- stdout\nPackage libsodium was not found in the pkg-config search path.\nPerhaps you should add the directory containing `libsodium.pc\'\nto the PKG_CONFIG_PATH environment variable\nNo package \'libsodium\' found\n"', ../src/libcore\result.rs:746
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```
On Windows with `MSYS` installed, `pkg-config` updated.
Trying to solve this for multiple hours.

**Comment by Sogomn** [comment]
Solved.
I had to move the `.pc`-files into the `pkgconfig` directory.

**Comment by Philipp91** [comment]
I get this error:
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "Failed to run `\"pkg-config\" \"--libs\" \"--cflags\" \"libsodium\"`: Das System kann die angegebene Datei nicht finden. (os error 2)"', ../src/libcore\result.rs:788

Most likely that's because pkg-config isn't installed properly. My attempts to install it have only resulted in a "Segmentation fault" output when running pkg-config.

I suggest reopening this issue. For a project that advertises a "portable, cross-compilable, installable" fork of an "easy-to-use" software library, there should be a documented, better way to use it on Windows than installing pkg-config first.
Let me know how I can help with this, or please point me to the solution if there is already one.

Related: https://github.com/dnaq/sodiumoxide/pull/135
