### ISSUE TITLE
Can algorithms / settings change in the future?

### ISSUE THREAD

**Issue by dpc** [dnaq/sodiumoxide#125]
I'm writing a backup application: https://github.com/dpc/rdedup that uses sodiumoxide and one things I'm wondering is can default underlying algorithms and settings (like `pwhash::pwhash::OPSLIMIT_SENSITIVE`) potentially change in the future? Can `box_` module point to different module implementing it? Any advise how to deal with that?

**Comment by dnaq** [comment]
Yes, they can change, but it's quite easy to deal with. For box_, just use
the specific box implementation, e.g.
crypto::box_::curve25519xsalsa20poly1305 instead of crypto::box_. For
pwhash you do the same and then either store the opslimit and memlimit
together with the hashed password or use the high level api that does it
for you.

**Comment by dpc** [comment]
Thanks! Is there a highlevel API that could do it for me already?

**Comment by dnaq** [comment]
pwhash::pwhash
