### ISSUE TITLE
Use a specific version of libsodium

### ISSUE THREAD

**Issue by dirvine** [dnaq/sodiumoxide#131]
If possible I think that a very valid issue we could tackle is to use a specific version of libsodium and build it with a build.rs. This ensures we know what is built and tested with various tags etc. 

A secondary but very beneficial feature of this would be cross compiled of rust code is now very simple, but libsodium requires separate build script etc. If we combine this then use of sodiumoxide in cross compile becomes much simpler. 

If we did a PR for this, how would it be received?

**Comment by dnaq** [comment]
I'm uncertain to be honest. When it comes to dynamic C-libraries I believe that they should be installed on the system and linked to (just like we are doing now). Otherwise if the underlying library has security issues we need to do a whole new update of `sodiumoxide` to not have the same issue. On the other hand I agree that the ergonomics could be better, somehow it would be nice if cargo allowed us to define external dependencies and print out a nicer error message if it's not found.

**Comment by dirvine** [comment]
Yes I am thinking more static link here. For dynamic then not so sure. I am not all that comfortable with dynamic link and security software. I fear injection etc. I think if the underlying lib has a security issue then update is good actually as it helps take users to a new patched version of both (perhaps).  

I wonder if there can be some comprimise, like conditional compilation or similar, although that screws with crates.io really?

**Comment by dnaq** [comment]
@dirvine If you find out a good way to solve this then please let me know and we'll discuss it further. Closing the issue for now.

**Comment by dirvine** [comment]
Wll do, we are working on some trial implementations and looking first at a sodiumoxide_extras crate.  The intention being to check these things out (also seeded rng etc.) and from there look to get these PR's to you if you see them as useful. 

Thanks again for the work you do here. We will try and help where we can.
