### ISSUE TITLE
Is there an easy way to store password based key derivation parameters?

### ISSUE THREAD

**Issue by sa2ajj** [dnaq/sodiumoxide#136]
In case I'd like to store the information for verifying a password, there's a nice function `crypto_pwhash_str`.  My use case is I'd like to store parameters required to derive a key to decrypt a particular secret key.  There does not seem to be anything "ready-to-use" available.

My question: is there anything that would make such a helper unreasonable  (for an arbitrary definition of "unreasonable")?

**Comment by dnaq** [comment]
There's nothing unreasonable about a small helper like that, however it's a wuite simple function to write do and for that reason I'd like to not add it to the sodiumoxide API (in order to not diverge too much from the libsodium API)

**Comment by sa2ajj** [comment]
If it's that simple a function, why there `crypto_pwhash_str` exists?  The latter stores:

* `salt`
* `opslimit`
* `memlimit`

And this helps a lot while _just_ verifying a password...

**Comment by dnaq** [comment]
The simple answer is that `crypto_pwhash_str` exists in sodiumoxide since it exists in libsodium. If libsodium were to add a similar function for key derivation I would add bindings to it in sodiumoxide. As you say yourself though, the only parameters needed to be able to derive the same key is `salt`, `opslimit` and `memlimit`, so a function like (in pseudo-rust)

```
fn store_stuff(salt, opslimit, memlimit) -> Vec<u8> {
   let mut v = Vec::with_capacity(size of salt + size of opslimit + size of memlimit);
   serialize_salt(salt, &mut v);
   serialize_opslimit(opslimit, &mut v);
   serialize_memlimit(memlimit, &mut v);
}
```
should do the trick...

**Comment by sa2ajj** [comment]
@dnaq: I'm sorry, I should have realised that this issue should have been raised with the upstream library.

Thank you for the snippet.
