### ISSUE TITLE
Can return values be ignored?

### ISSUE THREAD

**Issue by Philipp91** [dnaq/sodiumoxide#146]
Random example:
The C version of `crypto_box_curve25519xsalsa20poly1305` is tagged with `__attribute__ ((warn_unused_result))` (see https://github.com/jedisct1/libsodium/blob/master/src/libsodium/include/sodium/crypto_box_curve25519xsalsa20poly1305.h#L49), but sodiumoxide ignores it: https://github.com/dnaq/sodiumoxide/blob/0c9f41f0dfc085669c603f7fd0b393983947b266/src/crypto/box_/curve25519xsalsa20poly1305.rs#L84

I'm not sure if this is an issue at all and I can see that the obvioiusly important ones (like `crypto_box_curve25519xsalsa20poly1305_open`) are not ignored.

**Comment by dnaq** [comment]
The only way that function can fail is when the input is too short (the C API requires zero-padded messages), but since we add the correct amount of padding there's no way that can happen. That being said it might be prudent to check the return value and panic if it's not zero. I'd accept a pull request.
