### ISSUE TITLE
Rust 1.0 build failure: error: unresolved name `ffi::crypto_verify_64`

### ISSUE THREAD

**Issue by tarcieri** [dnaq/sodiumoxide#67]
```
Compiling sodiumoxide v0.0.5 (https://github.com/dnaq/sodiumoxide.git#00a0049f)
/Users/bascule/.cargo/git/checkouts/sodiumoxide-a55f941256560fcc/master/src/crypto/verify.rs:45:9: 45:30 error: unresolved name `ffi::crypto_verify_64`
/Users/bascule/.cargo/git/checkouts/sodiumoxide-a55f941256560fcc/master/src/crypto/verify.rs:45         ffi::crypto_verify_64(x, y) == 0
                                                                                                        ^~~~~~~~~~~~~~~~~~~~~
```

**Comment by dnaq** [comment]
Do you have a git-path dependency to sodiumoxide in your `Cargo.toml`? If so, then I believe you need to add one for `libsodium-sys` as well.

Basically what happens is that the master version of `sodiumoxide` depends on the master version of `libsodium-sys`. If you install from [http://crates.io] then you will pull in the correct version of `libsodium-sys` automatically, if you clone the git repository then you will also get an override configuration that builds the master version of `libsodium-sys`. I don't know of any better way to solve this problem, since best practice is to have a -sys library together with the actual library.

The easiest way is to depend on the version from crates.io. If there is functionality in the master repository that you need, then also add `libsodium-sys` as a dependency or path override. I will release a new version soon now that rust 1.0 has been released.

Let me know if this helps so that I can close the issue.

**Comment by tarcieri** [comment]
I was using the git dependency. Switching to the crates.io version fixed it, thanks!
