### ISSUE TITLE
Better support for manually incrementing nonces

### ISSUE THREAD

**Issue by dswd** [dnaq/sodiumoxide#90]
I had a use case where I wanted to manually increment a nonce (like the documentation of ChaCha20 says you should do). The current code makes implementing this a security minefield.
First of all, there is a method `gen_nonce` which randomly creates nonces when the documentation says you should not randomly create it but instead increment it because it is too short.
All the `Nonce` types are `Copy` which means you have to be very careful to not increment a copy.
I think it would be great if the `Nonce` types could just implement the `increment` method so users can use them without worrying about security.

**Comment by dnaq** [comment]
Hi. I believe that your'e correct in that primitives with 8-byte nonces shouldn't expose a `gen_nonce()` function. I will look at removing those for the next version of NaCl. As for nonces being `Copy` I don't really see that as a sodiumoxide specific issue, as a rust programmer I believe you should be expected to understand the ownership model of rust. Even if `Nonces` weren't `Copy` someone could still pass an old nonce instead of a new one.

That being said an `increment` function would probably be a good utility function to have. The reasons why they aren't any such functions in sodiumoxide are two-fold:

    1, There is no such function in `libsodium`
    2. Different protocols increment nonces in different ways, e.g. sender uses odd nonces, receiver uses even nonces or sender always uses nonces prefixed with `AA:AA:AA...` and receiver uses ones prefixed with `BB:BB:BB...`.

However `libsodium` 1.0.4 has added a `sodium_increment` function that I could add a binding to, and then maybe add an `increment()`-method to the nonce-types.

**Comment by dswd** [comment]
Thanks for considering my request. I want to clarify my problem with `Copy`. Please have a look at [this code](https://github.com/dswd/vpncloud.rs/blob/46728ce362e802f743a35184ad06807eefd26b0b/src/crypto.rs). It worked fine but when I tested it it turned out to not actually increment the nonce. The error is easy to make and hard to spot (Spoiler: it is in line 63).

**Comment by dnaq** [comment]
Yeah, that needs to be `ref mut nonce`. The choice is hard though, since a `Nonce` naturally is a `Copy` type, and the ergonomics of using `Nonces` would be worsened by not having them implement `Copy`.

**Comment by dswd** [comment]
Yes, I can see that. I can only think of very bulky ways to solve that like non-copy wrapper types or generic methods that accept copy and non-copy nonce types. Not very elegant either.

**Comment by dnaq** [comment]
Just pushed a fix for your issue, now all nonces have an `increment_le()` and an `increment_le_inplace()` method that can be used to help you with your use-case. I haven't released a new version with these changes yet.
